---
language: node_js
node_js:
  - "4"
  - "6"
  - "7"
  - "8"

sudo: false

cache:
  yarn: true

before_install:
  - npm config set spin false
  - npm install -g npm
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH=$HOME/.yarn/bin:$PATH

install:
  - yarn install

before_script:
  - yarn check --integrity

script:
  - yarn test
